#!/usr/bin/env bash

options=$(getopt -o d:a:ph --l help,directorio:,archivo:,pantalla -- "$@" 2> /dev/null)


eval set -- "$options"

while true; do
  case "$1" in
    -d|--directorio)
      DIRECTORIO="$2"; shift 2 ;;
    -a|--archivo)
      ARCHIVO="$2"; shift 2 ;;
    -p|--pantalla)
      PANTALLA=1; shift ;;
    -h|--help)
      echo "Uso: $0 -d <dir> -a <archivo> | -p"
      exit 0 ;;
    --)
      shift; break ;;
    *)
      break ;;
  esac
done


# 1. Validar que se pasó un directorio
if [ -z "$1" ]; then
  echo "Uso: $0 <DirectorioArchivos>"
  exit 1
fi

DIR="$1"

# 2. Recorrer todos los archivos .txt
for archivo in "$DIR"/*.txt; do
    awk -F"|" '
    {
        canal = $3
        tiempo[canal] += $4
        satisfaccion[canal] += $5
        cuenta[canal]++
    }
    END {
        for (c in cuenta) {
            printf "%s: tiempo_promedio=%.2f, satisfaccion_promedio=%.2f\n", \
                   c, tiempo[c]/cuenta[c], satisfaccion[c]/cuenta[c]
        }
    }
    ' "$archivo"
done