#!/bin/bash

options=$(getopt -o d:a:ph -l help,directorio:,archivo:,pantalla -- "$@" 2> /dev/null)

echo "$?"


eval set -- "$options"

while true; do
  case "$1" in
    -d|--directorio)
      DIR="$2";
      shift 2 ;;
    -a|--archivo)
      ARCHIVO="$2";
      shift 2 
      ;;
    -p|--pantalla)
      PANTALLA=1; shift ;;
    -h|--help)
      AYUDA=1; shift ;;
    --)
      shift; break ;;
    *)
      break ;;
  esac
done

echo $DIR $ARCHIVO $PANTALLA $AYUDA

# 2. Recorrer todos los archivos .txt
for arch in "$DIR"/*.txt; do
    awk -F"|" '
    {
        canal = $3
        tiempo[canal] += $4
        satisfaccion[canal] += $5
        cuenta[canal]++
    }
    END {
        for (c in cuenta) {
            printf "%s: tiempo_promedio=%.2f, satisfaccion_promedio=%.2f\n", \
                   c, tiempo[c]/cuenta[c], satisfaccion[c]/cuenta[c]
        }
    }
    ' "$archivo"
done